const dataObj = [
    {
        title: 'FullApp',
        tests: [
            'Active Tab Answers',
            'Active Tab Home',
            'Active Tab Search',
            'Active Tag Pinboards',
            'Auth Init Event',
            'Disable Action With Comment',
            'Frame Params',
            'Hidden Actions',
            'Init Event',
            'Load Event',
            'Path',
            'Set Runtime Filters',
            'Show Primary Navbar',
        ],
    },
    {
        title: 'Pinboard',
        tests: [
            'Auth Init Event',
            'Disable Action With Comment',
            'Enable Viz Transformations',
            'Frame Params',
            'Full Height',
            'Hidden Actions',
            'Init Event',
            'Load Event',
            'Modify Available Action',
            'Set Runtime Filters',
            'Without User Experience Customization',
        ],
    },
    {
        title: 'Search',
        tests: [
            'Answer Id',
            'Auth Init Event',
            'Collapse Data Panel',
            'Data Event',
            'Disable Action With Comment',
            'Enable Search Assist',
            'Frame Params',
            'Hidden Actions',
            'Hide Chart Or Table',
            'Hide Data Panels',
            'Init Event',
            'Load Event',
            'Modify Available Action',
            'Search Query',
            'Trigger',
            'Without User Experience Customization',
        ],
    },
    {
        title: 'Visualization',
        tests: [
            'Auth Init Event',
            'Data Event',
            'Disable Action With Comment',
            'Enable Viz Transformations',
            'Frame Params',
            'Hidden Actions',
            'Init Event',
            'Load Event',
            'Modify Available Actions',
            'Set Runtime Filters',
            'Without User Experience Customization',
        ],
    },
];

export default dataObj;
